# Generated by Django 4.2.2 on 2023-07-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_car_model3d_alter_company_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='model3d',
        ),
        migrations.AddField(
            model_name='car',
            name='body_type',
            field=models.CharField(blank=True, choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('supercar', 'Supercar'), ('pickup', 'Pickup'), ('hatchback', 'Hatchback'), ('convertible', 'Convertible'), ('minivan', 'Minivan'), ('coupe', 'Coupe'), ('sportscar', 'Sports car'), ('fastback', 'Fastback')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='engine_type',
            field=models.CharField(blank=True, choices=[('gasoline', 'Gasoline'), ('diesel', 'Diesel'), ('electric', 'Electric')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='torque',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
