# Generated by Django 4.2.2 on 2023-07-11 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='exclusive',
        ),
    ]
